services:
  backend:
    build:
      context: ./wizz-cloud_be
      dockerfile: Dockerfile
      target: development
    ports:
      - "1222:1222"
    volumes:
      - ./wizz-cloud_be:/app
      - /app/node_modules
      - ./wizz-cloud_be/cloud_storage:/app/cloud_storage
    env_file:
      - ./.env
    depends_on:
      - db
    command: npm run start:dev:nodemon

  frontend:
    build:
      context: ./wizz-cloud_fe
      dockerfile: Dockerfile
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./wizz-cloud_fe:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - backend
    command: npm run start:dev:nodemon

  db:
    image: postgres:13
    container_name: wizzcloud-db
    ports:
      - "5433:5432"
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 5

  migrations:
    image: migrate/migrate
    volumes:
      - ./wizz-cloud_be/var/migrations:/migrations
    command: ["-path", "/migrations", "-database", "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:latest
    container_name: wizzcloud-redis
    ports:
      - "6379:6379"
      
volumes:
  pgdata: